### ISSUE TITLE
Download of sources?

### ISSUE THREAD

**Issue by jmini** [jbangdev/jbang-eclipse#44]
When I import my jbang script containing following headers:

```java
///usr/bin/env jbang "$0" "$@" ; exit $?

//JAVA 17
//DEPS org.gitlab4j:gitlab4j-api:5.0.1
```

It works well:

![Jbang script in Eclipse IDE](https://user-images.githubusercontent.com/1222165/210788432-716f3119-0d20-440c-84a2-3a6914766534.png)

But when I want to inspect one the the class of the declared dependency, I do not have access to the sources:
![GitLabApi class opened in Eclipse without sources attached](https://user-images.githubusercontent.com/1222165/210788530-4dbce691-fb1c-4a00-b61a-bbd0d8f98d07.png)

Is this expected?

Tested version:
```
eclipse.buildId=4.26.0.20221201-1200

*** Plug-in Registry:
dev.jbang.eclipse.core (0.0.3.20230103-1009) "JBang Eclipse Core Plugin" [Active]
dev.jbang.eclipse.ui (0.0.3.20230103-1009) "JBang Eclipse UI Plugin" [Active]
```

**Comment by jmini** [comment]
Update if the sources jars exists locally in the local `.m2/repository` folder then it works as expected.

**Comment by fbricon** [comment]
indeed, automatic source download hasn't been implemented yet, but you can get that feature with the [PDE Source Lookup plugin](https://github.com/jbangdev/jbang-eclipse#recommended-3rd-party-plugins).
I discussed with @maxandersen about making jbang automatically download sources, but we're not there yet.

**Comment by maxandersen** [comment]
yeah so until now I've felt in principle that the IDE's should just do this as they know when the actual source code is requested (versus jbang always fetching the sources for every dependency) and the IDE can trivially today introspect the jars to lookup the sources. Unfortunately not many IDE's do - at least not eclipse nor vscode by default.

I still aren't fan of defaulting to download sources by default but might as well at least make it possible.

I suggest that `jbang edit` will do a resolve of dependencies including sources as thats the best point jbang knows if user are going to edit the project.

Might also consider adding a `--sources` flag to build/run.

I personally don't see a reason to download javadoc archives as modern IDE's don't rely on them anyway; but if anyone know of a reason to fill up the harddrive with `-javadoc.jar`s let me know ;)

**Comment by jmini** [comment]
I do not need the `-javadoc` jar. 
This is the default behavior of m2e when you add a dependency.

I am not even sure that the Java Eclipse project uses this jar. For me the Javadoc view in Eclipse is relying on the sources and not on the HTML pages inside the javadoc jar.

**Comment by fbricon** [comment]
Source downloads now work when using JBang 0.102+
